### ISSUE TITLE
Players drop a heart too.

### ISSUE THREAD

**Issue by DisbarredCord6** [sdphantomz3/LifestealMod#1]
When you kill a player, I gain a heart, however a heart gets dropped by the player as well.
![image](https://github.com/user-attachments/assets/4ac1fc5a-0f17-4325-af1b-f39e8cd22763)
![image](https://github.com/user-attachments/assets/cd41f74b-4464-4af1-9f5e-3fe9ef5d1660)

**Comment by DisbarredCord6** [comment]
Also I noticed that "redeem" is spelt incorrectly in the item description. 
![image](https://github.com/user-attachments/assets/9e44ab76-aa4e-470d-8b73-72e081901522)
Currently it is "radeem"

**Comment by sdphantomz3** [comment]
On it, will update tomorrow
 Thanks

**Comment by sdphantomz3** [comment]
**Fixed**
Modrinth: https://modrinth.com/mod/lifesteal-smp/version/1.2.0
Curseforge: https://www.curseforge.com/minecraft/mc-mods/lifestealsmp/files/5589524
