### ISSUE TITLE
Where is config

### ISSUE THREAD

**Issue by Ozn0k** [sdphantomz3/lifestealmod#16]
Hello, im using a macbook and i cant really find the config place. I wanna solve this asap because my friends are forcing me to.

**Comment by mrwiff** [comment]
you can configure the mod by putting lifestealmod.json into any text editor i believe

**Comment by Ozn0k** [comment]
What if there isn't the file lifestealmod.json?

**Comment by mrwiff** [comment]
you can find it in the config directory

**Comment by sdphantomz3** [comment]
Open .minecraft folder, then go to the config directory and there you will find the lifestealmod.json. You can find the .minecraft folder in Mac OS here I think: ~/Library/Application Support/minecraft
