### ISSUE TITLE
Heart glitch 

### ISSUE THREAD

**Issue by Armadidlo** [sdphantomz3/lifestealmod#4]
I was testing server with my friend and we realised that you can withdraw as many hearts as u want even if u have one this can ruin servers pls fix :)

**Comment by sdphantomz3** [comment]
Fixed:
- [Modrinth](https://modrinth.com/mod/lifesteal-smp/version/1.3.2)
- [Curseforge (under review)](https://www.curseforge.com/minecraft/mc-mods/lifestealsmp)
