### ISSUE TITLE
Health is restored when hearts are with drawn.

### ISSUE THREAD

**Issue by obscure021** [sdphantomz3/lifestealmod#5]
When the player withdraws heart, his health is restored, for example, if the player has 5 hp points with 10 max hearts, his health is restored (becomes 20 hp the max health) even if withdraws only heart.

**Comment by sdphantomz3** [comment]
This bug is fixed in the new update.
[Modrinth](https://modrinth.com/mod/lifesteal-smp/version/2.0)
[Curseforge](https://www.curseforge.com/minecraft/mc-mods/lifestealsmp)
