### ISSUE TITLE
Revive Item Usage

### ISSUE THREAD

**Issue by DisbarredCord6** [sdphantomz3/lifestealmod#6]
Reviving uses all the hearts/netherite in the players inventory.

**Comment by DisbarredCord6** [comment]
Also - will there ever be a way to make people be banned rather than be in spectator?

**Comment by sdphantomz3** [comment]
Yes, I am working on it.

**Comment by sdphantomz3** [comment]
The bugs are fixed in the new update.
[Modrinth](https://modrinth.com/mod/lifesteal-smp/version/2.0)
[Curseforge](https://www.curseforge.com/minecraft/mc-mods/lifestealsmp)
