### ISSUE TITLE
Getting above max hearts

### ISSUE THREAD

**Issue by Hu1k11** [sdphantomz3/lifestealmod#7]
In the 1.3.2 version if you are at the max of for me it was 30 hearts (60hp) and kill a player you can go above that limit

When a message comes up above the hotbar it has for example
message.lifestealmod.max_health

Could when losing all hearts you get banned when added??

Also when will the things listed in modrinth work in progress maybe be added?

**Comment by Hu1k11** [comment]
Just to add to the first point the heart gets added to the player and also gets throw out of the player who gets killed

**Comment by sdphantomz3** [comment]
The bugs are fixed in the new update.
[Modrinth](https://modrinth.com/mod/lifesteal-smp/version/2.0)
[Curseforge](https://www.curseforge.com/minecraft/mc-mods/lifestealsmp)
